name: "Speeches to JSON cron"

on:
  schedule:
    -   cron: "0 0 * * 0"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Sync
    timeout-minutes: 15
    steps:
      -   uses: actions/checkout@v2
      -   name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
      -   name: Setup dependencies
          run: pip install -r requirements.txt
      -   name: Get start date
          id: start_date
          run: echo "::set-output name=start_date::$(date -d "14 days ago" '+%Y-%m-%d')"
      -   name: Get end date
          id: end_date
          run: echo "::set-output name=end_date::$(date -d "7 days ago" '+%Y-%m-%d')"
      -   name: Run sync
          run: scrapy runspider crawling/spiders/statements.py -a start_date=${{ steps.start_date.outputs.start_date }} -a end_date=${{ steps.end_date.outputs.end_date }} -o statements.csv
      -   name: Commit changes
          uses: elstudio/actions-js-build/commit@v3
          with:
            commitMessage: Automated sync
