name: "Speeches to JSON cron"

on:
  push:
    branches:
      - master
  schedule:
    -   cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Sync
    timeout-minutes: 15
    steps:
      -   uses: actions/checkout@v2
      -   name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

      -   name: Setup dependencies
          run: |
            pip install -r requirements.txt
      -   name: Run sync
          run: scrapy runspider crawling/crawling/spiders/speeches.py -o speeches.json


      -   name: Commit changes
          uses: elstudio/actions-js-build/commit@v3
          with:
            commitMessage: Automated sync
